export const bollywoodData={
    data:[
        {
            wikiUrl:"https://en.wikipedia.org/wiki/Shah_Rukh_Khan",
            imgUrl:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Shah_Rukh_Khan_graces_the_launch_of_the_new_Santro.jpg/330px-Shah_Rukh_Khan_graces_the_launch_of_the_new_Santro.jpg",
            title:"",
    },
    {
        wikiUrl:"",
        imgUrl:"",
        title:"",
},
{
    wikiUrl:"",
    imgUrl:"",
    title:"",
},
    ]
}